classobject = classb()
classobject.setFirstname("Prashanth")
classobject.setLastname("Bethi")
classobject.setAge("25")
classobject.setAdress("California")
print classobject.getFirstname()
print classobject.getLastname()
print classobject.getAge()
print classobject.getAdress()